FROM python:3.10-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir kafka-python pandas python-dotenv

# Copy source code, data, and config
COPY src/ /app/src/
COPY data/ /app/data/
COPY .env /app/.env

# Set PYTHONPATH
ENV PYTHONPATH=/app

CMD ["python", "src/presentation/producer_launcher.py"]