"""
Airflow DAG for orchestrating the full tweet processing pipeline.

Flow architecture:
    1. Check Kafka availability
    2. Create required topics
    3. Start Producer (raw_tweets.csv → Kafka 'tweets')
    4. Start Flink Job (enrichment: 'tweets' → 'tweets_enriched')
    5. Start Consumer (enriched data → PostgreSQL + CSV files)


"""

import os
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.operators.python import PythonOperator
from airflow.operators.bash import BashOperator
import socket
import logging

logger = logging.getLogger(__name__)

# ==================== Config ====================

# Image names (automatically generated by Docker Compose)
PROJECT_NAME = "hv_9_kafka_flink_airflow"
PRODUCER_IMAGE = f"{PROJECT_NAME}-producer:latest"
CONSUMER_IMAGE = f"{PROJECT_NAME}-worker-consumer:latest"
NETWORK_MODE = f"{PROJECT_NAME}_kafka-network"

#  Kafka
KAFKA_BOOTSTRAP_SERVERS_INTERNAL = "kafka:29092"
KAFKA_BOOTSTRAP_SERVERS_EXTERNAL = "localhost:9092"
TOPIC_RAW = "tweets"
TOPIC_ENRICHED = "tweets_enriched"

# ==================== DEFAULT ARGUMENTS ====================

default_args = {
    'owner': 'data-engineering',
    'depends_on_past': False,
    'email': ['admin@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 2,
    'retry_delay': timedelta(minutes=2),
    'execution_timeout': timedelta(minutes=30),
}

# ==================== HELPER FUNCTIONS ====================

def check_kafka_ready(**context):
    """
    Check Kafka broker availability.

    Attempts to establish a TCP connection with Kafka.
    Raises an exception for retry if connection fails.
    """
    logger.info("Checking Kafka availability...")
    
    try:
        with socket.create_connection(("kafka", 29092), timeout=10):
            logger.info(" Kafka available")
            return True
    except OSError as e:
        logger.error(f" Kafka not available: {e}")
        raise Exception(f"Kafka broker not available: {e}")

# ==================== DAG DEFINITION ====================

with DAG(
    dag_id='tweet_enrichment_pipeline_v2',
    default_args=default_args,
    description='Tweet processing cicle: Producer → Flink (збагачення) → Consumer → CSV/DB',
    schedule_interval=None,  # Тригер - ручний запуск
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['kafka', 'flink', 'airflow', 'tweets', 'streaming', 'enrichment'],
    doc_md=__doc__,
) as dag:

    # ==================== TASK 1: Kafka check ====================
    
    check_kafka_availability = PythonOperator(
        task_id='check_kafka_availability',
        python_callable=check_kafka_ready,
        provide_context=True,
        doc_md="""
        ### Kafka Check
        Establishes a TCP connection with Kafka broker.
        Retries after 2 minutes if unavailable.
        """
    )
    
    # ==================== TASK 2: Topics creating ====================
    
     create_kafka_topics = BashOperator(
        task_id='create_kafka_topics',
        bash_command=f"""
            # Create topic for RAW data
            docker exec kafka kafka-topics --create --if-not-exists \
                --bootstrap-server {KAFKA_BOOTSTRAP_SERVERS_EXTERNAL} \
                --topic {TOPIC_RAW} \
                --partitions 3 \
                --replication-factor 1 \
                --config retention.ms=86400000 || true

            echo "Topic '{TOPIC_RAW}' created or already exists"

            # Create topic for ENRICHED data
            docker exec kafka kafka-topics --create --if-not-exists \
                --bootstrap-server {KAFKA_BOOTSTRAP_SERVERS_EXTERNAL} \
                --topic {TOPIC_ENRICHED} \
                --partitions 3 \
                --replication-factor 1 \
                --config retention.ms=86400000 || true

            echo "Topic '{TOPIC_ENRICHED}' created or already exists"

            # Verify created topics
            docker exec kafka kafka-topics --list \
                --bootstrap-server {KAFKA_BOOTSTRAP_SERVERS_EXTERNAL}
        """,
        doc_md="""
        ### Kafka Topic Creation
        - **tweets**: for RAW data from Producer
        - **tweets_enriched**: for enriched data from Flink

        Parameters:
        - Partitions: 3 (parallel processing)
        - Replication: 1 (dev environment)
        - Retention: 24 hours
        """
    )
    
    # ==================== TASK 3: START PRODUCER ====================
    
    run_kafka_producer = DockerOperator(
        task_id='run_kafka_producer',
        image=PRODUCER_IMAGE,
        container_name='airflow_producer_{{ ts_nodash }}',
        api_version='auto',
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode=NETWORK_MODE,
        environment={
            'KAFKA_BOOTSTRAP_SERVERS': KAFKA_BOOTSTRAP_SERVERS_INTERNAL,
            'KAFKA_TOPIC': TOPIC_RAW,
            'CSV_FILE': '/app/raw_tweets.csv',
            'MESSAGES_PER_SECOND': '5',  
        },
        mount_tmp_dir=False,
        tty=True,
        doc_md="""
        ### Kafka Producer
        Reads a CSV file with raw data and sends messages to topic 'tweets'.

        Message format:
```json
        {
            "author_id": "123456",
            "created_at": "2024-10-27T14:30:00",
            "text": "Sample tweet text..."
        }
```
        """
    )
    
    # ==================== TASK 4: START FLINK JOB ====================
    
    submit_flink_enrichment_job = BashOperator(
        task_id='submit_flink_enrichment_job',
        bash_command=f"""
            echo " Start Flink Job for data enrichment..."
            
            # Run Python Flink Job inside JobManager container
        docker exec flink-jobmanager \
            flink run \
            --python /opt/flink/usrlib/tweet_enrichment_processor.py \
            --jobmanager flink-jobmanager:8081 \
            --detached

        echo "Flink Job started in detached mode"
        echo "Check status: http://localhost:8081"
            
            # Wait 10 seconds for job startup
            sleep 10
        """,
        doc_md="""
        ### Flink Enrichment Job
    Starts Apache Flink Job for stream enrichment.

    Enrichment includes:
    - **text_length**: text length
    - **processed_at**: processing timestamp
    - **company**: detected company (Apple/Google/Microsoft/Amazon)
    - **priority**: priority based on length (HIGH/MEDIUM/LOW)

    Input: topic 'tweets'
    Output: topic 'tweets_enriched'
        """
    )
    
    # ==================== TASK 5: START CONSUMER ====================
    
    run_final_consumer = DockerOperator(
        task_id='run_final_consumer',
        image=CONSUMER_IMAGE,
        container_name='airflow_consumer_{{ ts_nodash }}',
        api_version='auto',
        auto_remove=True,
        docker_url="unix://var/run/docker.sock",
        network_mode=NETWORK_MODE,
        environment={
            'KAFKA_BOOTSTRAP_SERVERS': KAFKA_BOOTSTRAP_SERVERS_INTERNAL,
            'KAFKA_TOPIC': TOPIC_ENRICHED,  
            'POSTGRES_HOST': 'postgres',
            'POSTGRES_PORT': '5432',
            'POSTGRES_USER': 'admin',
            'POSTGRES_PASSWORD': 'admin123',
            'POSTGRES_DB': 'tweets_db',
            'CSV_OUTPUT_DIR': '/app/output',
        },
        mount_tmp_dir=False,
        tty=True,
        execution_timeout=timedelta(minutes=15),
        doc_md="""
        ### Final Consumer
    Consumes enriched data from topic 'tweets_enriched' and stores it in:

    1. **PostgreSQL**: table `tweets_enriched`
    2. **CSV files**: format `tweets_dd_mm_yyyy_hh_mm.csv`

    CSV splitting: by minute (each minute = new file)
        """
    )
    
    # ==================== EXECUTION FLOW DEFINITION ====================
    
    """
    Execution graph:
    
    check_kafka_availability 
        ↓
    create_kafka_topics
        ↓
    run_kafka_producer
        ↓
    submit_flink_enrichment_job
        ↓
    run_final_consumer
    """
    
    (
        check_kafka_availability 
        >> create_kafka_topics 
        >> run_kafka_producer 
        >> submit_flink_enrichment_job 
        >> run_final_consumer
    )